name: colon_pnmf
seed: 67
dataset: colon
output_dir: outputs/colon_test

preprocessing:
  spatial_scale: 50.0
  h5ad_path: /gladstone/engelhardt/lab/jcai/hdp/results/merfish/HuColonCa-FFPE-ImmuOnco-LH_VMSC02001_20220427_seed_2024_K100_T500_baysor_adata_mingenes0_mincounts10.h5ad
  labels_path: /gladstone/engelhardt/pelka-collaboration/Vizgen_HuColonCa_20220427_prediction-labels.csv
  group_column: cl46v1SubShort_ds
  subsample: null
  min_group_fraction: 0.01

model:
  loadings_mode: multiplicative
  n_components: 12
  mode: expanded
  training_mode: standard
  E: 3
  spatial: false
  prior: GaussianPrior

training:
  max_iter: 10
  learning_rate: 2e-3
  optimizer: Adam
  tol: 1e-4
  verbose: false
  device: gpu
  batch_size: 13000
  y_batch_size: 492
  shuffle: true
