name: sdmbench_lcgp
seed: 67
dataset: sdmbench
output_dir: outputs/sdmbench_test/151509

preprocessing:
  spatial_scale: 50.0
  path: /gladstone/engelhardt/home/lchumpitaz/gitclones/SDMBench/Data/151509.h5ad
  region_column: Region
  min_group_fraction: 0.01

model:
  loadings_mode: multiplicative
  n_components: 12
  mode: expanded
  training_mode: standard
  E: 3
  spatial: true
  prior: LCGP
  sigma: 1.0
  kernel: Matern32
  lengthscale: 10.0
  train_lengthscale: false
  local: true
  K: 50
  precompute_knn: true

training:
  max_iter: 10
  learning_rate: 2e-3
  optimizer: Adam
  tol: 1e-4
  verbose: false
  device: gpu
  batch_size: 4221
  y_batch_size: 2000
  shuffle: true
