name: merfish_svgp
seed: 67
dataset: merfish
output_dir: outputs/merfish_test

preprocessing:
  spatial_scale: 50.0
  group_column: Cell_class
  min_group_fraction: 0.01

model:
  loadings_mode: multiplicative
  n_components: 12
  mode: expanded
  training_mode: standard
  E: 3
  spatial: true
  prior: SVGP
  sigma: 1.0
  kernel: Matern32
  lengthscale: 10.0
  train_lengthscale: false
  cholesky_mode: exp
  diagonal_only: false
  num_inducing: 3000

training:
  max_iter: 10
  learning_rate: 2e-3
  optimizer: Adam
  tol: 1e-4
  verbose: false
  device: gpu
  batch_size: 15000
  y_batch_size: 161
  shuffle: true
