name: slideseq_mggp_svgp
seed: 67
dataset: slideseq
output_dir: outputs/slideseq_test

preprocessing:
  spatial_scale: 50.0
  filter_mt: true
  min_counts: 100
  min_cells: 10

model:
  loadings_mode: multiplicative
  mode: expanded
  E: 3
  n_components: 10
  training_mode: standard
  spatial: true
  prior: SVGP
  lengthscale: 8.0
  kernel: Matern32
  sigma: 1.0
  train_lengthscale: false
  num_inducing: 3000
  diagonal_only: false
  cholesky_mode: exp
  groups: true
  inducing_allocation: derived
  group_diff_param: 1.0

training:
  max_iter: 200
  learning_rate: 2e-3
  optimizer: Adam
  tol: 1e-4
  verbose: false
  device: gpu
  batch_size: 7000
  y_batch_size: 2000
  shuffle: true
